version: "3.9"

services:
  app:
    container_name: flask-api

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    restart: unless-stopped

  prometheus:
    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - app

    restart: unless-stopped